from __future__ import annotations

from datetime import date
from typing import TYPE_CHECKING
from uuid import uuid4

from sqlalchemy import Date, Float, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TimestampMixin

if TYPE_CHECKING:
    from app.models.meal_plan_item import MealPlanItem
    from app.models.user import User
    from app.models.user_goal import UserGoal


class MealPlan(Base, TimestampMixin):
    """
    A planned daily meal structure for a user.

    A plan can be manually created or generated by a simple rule-based engine.
    """

    __tablename__ = "meal_plans"

    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid4()),
    )
    user_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("users.id", ondelete="CASCADE"),
        index=True,
        nullable=False,
    )
    goal_id: Mapped[str | None] = mapped_column(
        String(36),
        ForeignKey("user_goals.id", ondelete="SET NULL"),
        index=True,
        nullable=True,
    )

    plan_date: Mapped[date] = mapped_column(
        Date,
        index=True,
        nullable=False,
    )
    generation_mode: Mapped[str] = mapped_column(
        String(30),
        default="manual",
        nullable=False,
    )
    notes: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )

    total_calories: Mapped[float] = mapped_column(
        Float,
        default=0,
        nullable=False,
    )
    total_protein_g: Mapped[float] = mapped_column(
        Float,
        default=0,
        nullable=False,
    )
    total_carbs_g: Mapped[float] = mapped_column(
        Float,
        default=0,
        nullable=False,
    )
    total_fat_g: Mapped[float] = mapped_column(
        Float,
        default=0,
        nullable=False,
    )

    item_count: Mapped[int] = mapped_column(
        Integer,
        default=0,
        nullable=False,
    )

    user: Mapped[User] = relationship("User", back_populates="meal_plans")
    goal: Mapped[UserGoal | None] = relationship("UserGoal")
    items: Mapped[list[MealPlanItem]] = relationship(
        "MealPlanItem",
        back_populates="meal_plan",
        cascade="all, delete-orphan",
        order_by="MealPlanItem.position.asc()",
    )